# Generated by Django 5.0 on 2023-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='cedula',
            field=models.CharField(default='cedula', max_length=30),
        ),
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='cedulaE',
            field=models.CharField(default='cedula Extranjeria', max_length=30),
        ),
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='tarjeta_identidad',
            field=models.CharField(default='tarjeta identidad', max_length=30),
        ),
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='tributaria',
            field=models.CharField(default='tributaria', max_length=30),
        ),
        migrations.AddField(
            model_name='tipopredio',
            name='rural',
            field=models.CharField(default='rural', max_length=30),
        ),
        migrations.AddField(
            model_name='tipopredio',
            name='urbano',
            field=models.CharField(default='urbano', max_length=30),
        ),
        migrations.AddField(
            model_name='tipospropietario',
            name='juridico',
            field=models.CharField(default='juridico', max_length=30),
        ),
        migrations.AddField(
            model_name='tipospropietario',
            name='natural',
            field=models.CharField(default='natural', max_length=30),
        ),
    ]
