# Generated by Django 5.0 on 2023-12-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0002_tiponumerodocumento_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='cedulaE',
        ),
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='tarjeta_identidad',
        ),
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='tributaria',
        ),
        migrations.RemoveField(
            model_name='tipopredio',
            name='rural',
        ),
        migrations.RemoveField(
            model_name='tipopredio',
            name='urbano',
        ),
        migrations.RemoveField(
            model_name='tipospropietario',
            name='juridico',
        ),
        migrations.RemoveField(
            model_name='tipospropietario',
            name='natural',
        ),
    ]
