# Generated by Django 5.0 on 2023-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0003_remove_tiponumerodocumento_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='tiposDocumento',
            field=models.CharField(choices=[('CC', 'Cedula De Ciudadania'), ('TI', 'Tarjeta De Identidad'), ('NT', 'Numero De Identificacion Tributaria'), ('CE', 'Cedula De Extranjeria')], default='CC', max_length=10),
        ),
    ]
