# Generated by Django 5.0 on 2023-12-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0004_tiponumerodocumento_tiposdocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='tiposDocumento',
        ),
    ]
