# Generated by Django 5.0 on 2023-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0006_tiponumerodocumento_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponumerodocumento',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula De Ciudadania'), ('TI', 'Tarjeta De Identidad'), ('NT', 'Numero De Identificacion Tributaria'), ('CE', 'Cedula De Extranjeria')], default='CC', max_length=30, unique=True),
        ),
    ]
