# Generated by Django 5.0 on 2023-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0007_alter_tiponumerodocumento_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopredio',
            name='tipoPredio',
            field=models.CharField(choices=[('ru', 'rural'), ('ur', 'urbano')], default='ru', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='tipospropietario',
            name='tipoPropietario',
            field=models.CharField(choices=[('na', 'natural'), ('ju', 'juridico')], default='na', max_length=30, unique=True),
        ),
    ]
