# Generated by Django 5.0 on 2024-01-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0009_tipopropietario'),
        ('predio', '0024_alter_predio_tipo_alter_propietario_tipodocumento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tiposPropietario',
        ),
        migrations.RemoveField(
            model_name='tiponumerodocumento',
            name='tipoDocumento',
        ),
        migrations.RemoveField(
            model_name='tipopredio',
            name='tipoPredio',
        ),
        migrations.AddField(
            model_name='tiponumerodocumento',
            name='nombre',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Tipo De Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopredio',
            name='nombre',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Tipo De Predio'),
            preserve_default=False,
        ),
    ]
