# Generated by Django 5.0 on 2023-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='numeroCatastral',
            field=models.CharField(default='na', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='numeroMatricula',
            field=models.CharField(default='na', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='propietario',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], default='urbano', max_length=6),
        ),
    ]
