# Generated by Django 5.0 on 2023-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0003_propietario_alter_predio_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='propietario',
        ),
        migrations.AddField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(to='predio.propietario'),
        ),
    ]
