# Generated by Django 5.0 on 2023-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0005_alter_propietario_nombrepropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(related_name='predios', to='predio.propietario'),
        ),
    ]
