# Generated by Django 5.0 on 2023-12-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0006_alter_predio_propietarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='propietarios',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombrePropietario',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='predio',
            name='propietarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predios', to='predio.propietario'),
        ),
    ]
