# Generated by Django 5.0 on 2023-12-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0007_remove_predio_propietarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ForeignKey(default='sin propietario', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='predios', to='predio.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombrePropietario',
            field=models.CharField(default='sin propietario', max_length=30),
        ),
    ]
