# Generated by Django 5.0 on 2023-12-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0008_alter_predio_propietarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predios', to='predio.propietario'),
        ),
    ]
