# Generated by Django 5.0 on 2023-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0011_alter_predio_propietarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='propietarios',
        ),
        migrations.AddField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='predios', to='predio.propietario'),
        ),
    ]
