# Generated by Django 5.0 on 2023-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0013_alter_predio_propietarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(default='sin propietario', to='predio.propietario'),
        ),
    ]
