# Generated by Django 5.0 on 2023-12-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0015_alter_predio_propietarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(blank=True, to='predio.propietario'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombrePropietario',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipoDocumento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipoPropietario',
            field=models.CharField(max_length=9),
        ),
    ]
