# Generated by Django 5.0 on 2023-12-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0003_remove_tiponumerodocumento_cedula_and_more'),
        ('predio', '0016_alter_predio_propietarios_alter_predio_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tiponumerodocumento'),
        ),
    ]
