# Generated by Django 5.0 on 2023-12-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0007_alter_tiponumerodocumento_tipodocumento'),
        ('predio', '0017_alter_propietario_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tiponumerodocumento', to_field='tipoDocumento'),
        ),
    ]
