# Generated by Django 5.0 on 2023-12-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0008_tipopredio_tipopredio_and_more'),
        ('predio', '0018_alter_propietario_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tipopredio', to_field='tipoPredio'),
        ),
    ]
