# Generated by Django 5.0 on 2024-01-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0021_alter_propietario_tipopropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipoPropietario',
            field=models.CharField(default='na', max_length=9),
        ),
    ]
