# Generated by Django 5.0 on 2024-01-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0009_tipopropietario'),
        ('predio', '0023_alter_propietario_tipopropietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tipopredio'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tiponumerodocumento'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipoPropietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dominios.tipopropietario'),
        ),
    ]
